application: morsee-line-bot
version: v3

runtime: go
api_version: go1
threadsafe: yes

default_expiration: 1d

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 120

handlers:
  - url: /.*
    script: _go_app
    secure: always

env_variables:
  CHANNEL_SECRET: "94deec3d0d8ce2bbaf5327cc76484484"
  CHANNEL_TOKEN: "R4/GLljAe+PP8nzjQ4934sjN3NVsnoRXpYnZsoCJiqoiAi5Mbh2uYgjGoE0N/dRnFLt0m5RXWLFD0GnYI9ZwEHbZJ+ihI9k4g3QihXn0fiB1tz0izO+s92L1s6Hxh+zspaFRxMToo8m3aNZ07mVE7QdB04t89/1O/w1cDnyilFU="
